fred.category <- function(f, category_id=NULL, ...) get.fred(f, "fred/category", c(category_id=category_id, ...))
fred.category.children <- function(f, category_id=NULL, ...) get.fred(f, "fred/category/children", c(category_id=category_id, ...))
fred.category.related <- function(f, category_id, ...) get.fred(f, "fred/category/related", c(category_id=category_id, ...))
fred.category.series <- function(f, category_id, ...) get.fred(f, "fred/category/series", c(category_id=category_id, ...))
fred.category.tags <- function(f, category_id, ...) get.fred(f, "fred/category/tags", c(category_id=category_id, ...))
fred.category.related_tags <- function(f, category_id, tag_names, ...) get.fred(f, "fred/category/related_tags", c(category_id=category_id, tag_names=tag_names, ...))
