fred.category <- function(f, category_id=NULL, ...) get.fred(f, "fred/category", c(category_id=category_id, ...))
fred.category.children <- function(f, category_id=NULL, ...) get.fred(f, "fred/category/children", c(category_id=category_id, ...))
fred.category.related <- function(f, category_id, ...) get.fred(f, "fred/category/related", c(category_id=category_id, ...))
fred.category.series <- function(f, category_id, ...) get.fred(f, "fred/category/series", c(category_id=category_id, ...))
fred.category.tags <- function(f, category_id, ...) get.fred(f, "fred/category/tags", c(category_id=category_id, ...))
fred.category.related_tags <- function(f, category_id, tag_names, ...) get.fred(f, "fred/category/related_tags", c(category_id=category_id, tag_names=tag_names, ...))
fred.releases <- function(f, ...) get.fred(f, "fred/releases", c(...))
fred.releases.dates <- function(f, ...) get.fred(f, "fred/releases/dates", c(...))
fred.release <- function(f, release_id, ...) get.fred(f, "fred/release", c(release_id=release_id, ...))
fred.release.dates <- function(f, release_id, ...) get.fred(f, "fred/release/dates", c(release_id=release_id, ...))
fred.release.series <- function(f, release_id, ...) get.fred(f, "fred/release/series", c(release_id=release_id, ...))
fred.release.sources <- function(f, release_id, ...) get.fred(f, "fred/release/sources", c(release_id=release_id, ...))
fred.release.tags <- function(f, release_id, ...) get.fred(f, "fred/release/tags", c(release_id=release_id, ...))
fred.release.related_tags <- function(f, release_id, tag_names, ...) get.fred(f, "fred/release/related_tags", c(release_id=release_id, tag_names=tag_names, ...))
