fred.category <- function(f, category_id=NULL, ...) get.fred(f, "fred/category", c(category_id=category_id, ...))
fred.category.children <- function(f, category_id=NULL, ...) get.fred(f, "fred/category/children", c(category_id=category_id, ...))
fred.category.related <- function(f, category_id, ...) get.fred(f, "fred/category/related", c(category_id=category_id, ...))
fred.category.series <- function(f, category_id, ...) get.fred(f, "fred/category/series", c(category_id=category_id, ...))
fred.category.tags <- function(f, category_id, ...) get.fred(f, "fred/category/tags", c(category_id=category_id, ...))
fred.category.related_tags <- function(f, category_id, tag_names, ...) get.fred(f, "fred/category/related_tags", c(category_id=category_id, tag_names=tag_names, ...))
fred.releases <- function(f, ...) get.fred(f, "fred/releases", c(...))
fred.releases.dates <- function(f, ...) get.fred(f, "fred/releases/dates", c(...))
fred.release <- function(f, release_id, ...) get.fred(f, "fred/release", c(release_id=release_id, ...))
fred.release.dates <- function(f, release_id, ...) get.fred(f, "fred/release/dates", c(release_id=release_id, ...))
fred.release.series <- function(f, release_id, ...) get.fred(f, "fred/release/series", c(release_id=release_id, ...))
fred.release.sources <- function(f, release_id, ...) get.fred(f, "fred/release/sources", c(release_id=release_id, ...))
fred.release.tags <- function(f, release_id, ...) get.fred(f, "fred/release/tags", c(release_id=release_id, ...))
fred.release.related_tags <- function(f, release_id, tag_names, ...) get.fred(f, "fred/release/related_tags", c(release_id=release_id, tag_names=tag_names, ...))
fred.series <- function(f, series_id, ...) get.fred(f, "fred/series", c(series_id=series_id, ...))
fred.series.categories <- function(f, series_id, ...) get.fred(f, "fred/series/categories", c(series_id=series_id, ...))
fred.series.observations <- function(f, series_id, ...) get.fred(f, "fred/series/observations", c(series_id=series_id, ...))
fred.series.release <- function(f, series_id, ...) get.fred(f, "fred/series/release", c(series_id=series_id, ...))
fred.series.search <- function(f, search_text, ...) get.fred(f, "fred/series/search", c(search_text=search_text, ...))
fred.series.search.tags <- function(f, series_search_text, ...) get.fred(f, "fred/series/search/tags", c(series_search_text=series_search_text, ...))
fred.series.search.related_tags <- function(f, series_search_text, tag_names, ...) get.fred(f, "fred/series/search/related_tags", c(series_search_text=series_search_text, tag_names=tag_names, ...))
fred.series.tags <- function(f, series_id, ...) get.fred(f, "fred/series/tags", c(series_id=series_id, ...))
fred.series.updates <- function(f, ...) get.fred(f, "fred/series/updates", c(...))
fred.series.vintagedates <- function(f, series_id, ...) get.fred(f, "fred/series/vintagedates", c(series_id=series_id, ...))
fred.sources <- function(f, ...) get.fred(f, "fred/sources", c(...))
fred.source <- function(f, source_id, ...) get.fred(f, "fred/source", c(source_id=source_id, ...))
fred.source.releases <- function(f, source_id, ...) get.fred(f, "fred/source/releases", c(source_id=source_id, ...))
fred.tags <- function(f, ...) get.fred(f, "fred/tags", c(...))
fred.related_tags <- function(f, tag_names, ...) get.fred(f, "fred/related_tags", c(tag_names=tag_names, ...))
fred.tags.series <- function(f, tag_names, ...) get.fred(f, "fred/tags/series", c(tag_names=tag_names, ...))
